try {
    fetch('/test');
} catch(err) {
    console.log(123);
}
